package ai.eight24family.conch.domain

/**
 * Algorithm of the imported / generated keypair.
 *
 * Generated by the app are always [ED25519] (small, modern, default
 * everywhere). [RSA] / [ECDSA] / [DSA] / [UNKNOWN] cover keys imported
 * from external sources (file pickers, USB drives) — labelled for
 * display only; the SSH stack treats the private bytes as opaque.
 *
 * [SK_ED25519] / [SK_ECDSA_NISTP256] are FIDO2 security keys — the
 * private bytes live on the hardware token (YubiKey, Nitrokey,
 * SoloKey, etc.) and never enter the device. They wire format on the
 * server side as `sk-ssh-ed25519@openssh.com` /
 * `sk-ecdsa-sha2-nistp256@openssh.com` (any OpenSSH ≥ 8.2 understands
 * them).
 *
 * `SshKeyEntity.toDomain` falls back to ED25519 on `valueOf()` failure,
 * so adding a new enum value here does NOT need a Room migration; rows
 * stored under an old version simply read as ED25519 until next upsert.
 */
enum class SshKeyType {
    ED25519, RSA, ECDSA, DSA, UNKNOWN,
    SK_ED25519, SK_ECDSA_NISTP256,
}

/**
 * Where a security-key credential expects to be presented when
 * authenticating. `EITHER` means we don't pin the user to a transport
 * (the same key may be USB now, NFC tomorrow). USB / NFC variants exist
 * for keys that physically only support one form factor.
 */
enum class SecurityKeyTransport { USB, NFC, EITHER }

/**
 * Extra fields that only exist for security keys. Null for software
 * keys — keeps the DB column count down without splitting `SshKey` into
 * two tables. Saved as a separate object so the common `SshKey` shape
 * stays compact at every callsite that doesn't care about FIDO.
 */
data class SshKeySecurityInfo(
    /**
     * The credential id the authenticator returned at registration time.
     * Opaque bytes (CTAP2 spec calls this the "credential ID"). Replayed
     * verbatim in the `allowList` of every later getAssertion call.
     */
    val credentialIdBase64: String,
    /**
     * "rpId" in CTAP2 vocabulary, "application" in OpenSSH SK file format.
     * Default `ssh:` matches what `ssh-keygen -t ed25519-sk` writes; the
     * server doesn't care what the value is, only that it matches between
     * registration and signing.
     */
    val application: String,
    val transport: SecurityKeyTransport,
)

data class SshKey(
    val id: String,
    val name: String,
    val type: SshKeyType,
    val publicKey: String,
    val fingerprint: String,
    val comment: String,
    val createdAt: Long,
    /**
     * Populated only when [type] is `SK_*`. For software keys this is
     * always null — keep optional rather than forcing every caller to
     * thread an empty stub.
     */
    val securityInfo: SshKeySecurityInfo? = null,
)

data class SshKeySecrets(
    val privateKeyPem: String,
    val passphrase: String? = null
)
