package ai.eight24family.conch.agent.codex

import ai.eight24family.conch.agent.AgentMessage
import ai.eight24family.conch.data.prefs.AgentApprovalMode
import ai.eight24family.conch.util.SilentlyTry
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.add
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject

/**
 * Wire codec for **`codex app-server`** — Codex's bidirectional JSON-RPC
 * channel (JSONL over stdio, NO `"jsonrpc"` field). This is the transport
 * codex's own IDE clients ride; it is what makes Codex chats interactive
 * at parity with the Claude control protocol: live approval prompts,
 * `request_user_input` multi-choice questions, real `turn/interrupt`,
 * live compaction items and `thread/tokenUsage/updated` counters.
 *
 * Every shape below is verified against the TS bindings generated by the
 * INSTALLED binary (`codex app-server generate-ts`, codex-cli 0.139.0,
 * dump 2026-06-13) — NOT against docs, which contradicted each other:
 *
 *  - Client→server requests: `{method, id, params}`; responses come back
 *    as `{id, result}` / `{id, error}`. `RequestId = string | number`.
 *  - Server→client REQUESTS (have `id`, MUST be answered with a JSON-RPC
 *    response): `item/commandExecution/requestApproval` →
 *    `{decision: "accept"|"acceptForSession"|"decline"|"cancel"}`;
 *    `item/fileChange/requestApproval` → same decisions;
 *    `item/tool/requestUserInput` → `{answers: {<qid>: {answers: [..]}}}`
 *    (questions: `{id, header, question, isOther, isSecret, options:
 *    [{label, description}] | null}`);
 *    `mcpServer/elicitation/request` → `{action: "decline", content: null}`.
 *  - Notifications (no `id`, never answered): `thread/started`,
 *    `turn/started|completed`, `item/started|completed`,
 *    `item/agentMessage/delta`, the `item/reasoning/…Delta` family,
 *    `thread/tokenUsage/updated` (TokenUsageBreakdown: totalTokens /
 *    inputTokens / cachedInputTokens / outputTokens /
 *    reasoningOutputTokens), `turn/plan/updated`, `error`, …
 *  - Handshake: `initialize` (capabilities.experimentalApi=true unlocks
 *    the experimental request_user_input surface) → response → client
 *    notification `{"method":"initialized"}`.
 */
internal object CodexAppServerWire {

    val json = Json { ignoreUnknownKeys = true; isLenient = true }

    // ────────── Encoding: client → server ──────────

    fun encodeInitialize(id: Long, appVersion: String): String = buildJsonObject {
        put("method", "initialize")
        put("id", id)
        putJsonObject("params") {
            putJsonObject("clientInfo") {
                put("name", "conch")
                put("title", "conch")
                put("version", appVersion)
            }
            putJsonObject("capabilities") {
                // Experimental API gate — item/tool/requestUserInput and
                // friends only flow when the client opts in.
                put("experimentalApi", true)
                put("requestAttestation", false)
            }
        }
    }.toString()

    fun encodeInitialized(): String = """{"method":"initialized"}"""

    fun encodeThreadStart(
        id: Long,
        model: String?,
        cwd: String?,
        approval: AgentApprovalMode,
    ): String = buildJsonObject {
        put("method", "thread/start")
        put("id", id)
        putJsonObject("params") {
            model?.takeIf { it.isNotBlank() }?.let { put("model", it) }
            cwd?.takeIf { it.isNotBlank() }?.let { put("cwd", it) }
            val (policy, sandbox) = approvalToPolicy(approval)
            put("approvalPolicy", policy)
            put("sandbox", sandbox)
        }
    }.toString()

    fun encodeThreadResume(
        id: Long,
        threadId: String,
        model: String?,
        cwd: String?,
        approval: AgentApprovalMode,
    ): String = buildJsonObject {
        put("method", "thread/resume")
        put("id", id)
        putJsonObject("params") {
            put("threadId", threadId)
            model?.takeIf { it.isNotBlank() }?.let { put("model", it) }
            cwd?.takeIf { it.isNotBlank() }?.let { put("cwd", it) }
            val (policy, sandbox) = approvalToPolicy(approval)
            put("approvalPolicy", policy)
            put("sandbox", sandbox)
        }
    }.toString()

    /**
     * One user turn. Unlike the Claude persistent channel, model / effort /
     * approval / cwd are PER-TURN overrides here ("for this turn and
     * subsequent turns") — mid-chat picker changes need no process restart.
     */
    fun encodeTurnStart(
        id: Long,
        threadId: String,
        text: String,
        model: String?,
        effort: String?,
        approval: AgentApprovalMode?,
        cwd: String?,
        /** Absolute paths of images already uploaded to the server. Emitted as
         *  v2 `localImage` input items so the model actually SEES the pixels —
         *  before this, attachments reached the model only as a path string in
         *  the prose (audit 2026-06-14). */
        imagePaths: List<String> = emptyList(),
    ): String = buildJsonObject {
        put("method", "turn/start")
        put("id", id)
        putJsonObject("params") {
            put("threadId", threadId)
            putJsonArray("input") {
                add(buildJsonObject {
                    put("type", "text")
                    put("text", text)
                    putJsonArray("text_elements") {}
                })
                // v2 UserInput localImage variant — verified via
                // `codex app-server generate-ts` (v2/UserInput, codex-cli 0.80.0):
                // { "type": "localImage", path }. References the uploaded file.
                imagePaths.forEach { p ->
                    if (p.isNotBlank()) add(buildJsonObject {
                        put("type", "localImage")
                        put("path", p)
                    })
                }
            }
            model?.takeIf { it.isNotBlank() }?.let { put("model", it) }
            effort?.takeIf { it.isNotBlank() }?.let { put("effort", it) }
            cwd?.takeIf { it.isNotBlank() }?.let { put("cwd", it) }
            approval?.let { put("approvalPolicy", approvalToPolicy(it).first) }
        }
    }.toString()

    /**
     * Start a code review on the current thread (`review/start`). Verified v2
     * shape via `codex app-server generate-ts` (codex-cli 0.80.0):
     * ReviewStartParams = { threadId, target: ReviewTarget, delivery }; the
     * response is { turn } and the review streams like a turn, ending with an
     * `exitedReviewMode` item carrying the result. [baseBranch] null/blank →
     * review the UNCOMMITTED changes (the "before I push" case); otherwise
     * review vs that base branch. delivery "inline" runs on this thread.
     */
    fun encodeReviewStart(
        id: Long,
        threadId: String,
        baseBranch: String?,
        delivery: String = "inline",
    ): String = buildJsonObject {
        put("method", "review/start")
        put("id", id)
        putJsonObject("params") {
            put("threadId", threadId)
            putJsonObject("target") {
                if (baseBranch.isNullOrBlank()) {
                    put("type", "uncommittedChanges")
                } else {
                    put("type", "baseBranch")
                    put("branch", baseBranch)
                }
            }
            put("delivery", delivery)
        }
    }.toString()

    fun encodeTurnInterrupt(id: Long, threadId: String, turnId: String): String = buildJsonObject {
        put("method", "turn/interrupt")
        put("id", id)
        putJsonObject("params") {
            put("threadId", threadId)
            put("turnId", turnId)
        }
    }.toString()

    // ── Responses to SERVER-initiated requests (echo the server's id) ──

    /** commandExecution / fileChange approvals share the decision enum. */
    fun encodeApprovalDecision(requestId: JsonElement, decision: String): String = buildJsonObject {
        put("id", requestId)
        putJsonObject("result") { put("decision", decision) }
    }.toString()

    /** `item/tool/requestUserInput` answer: question id → chosen labels. */
    fun encodeUserInputAnswers(requestId: JsonElement, answersByQid: Map<String, List<String>>): String =
        buildJsonObject {
            put("id", requestId)
            putJsonObject("result") {
                putJsonObject("answers") {
                    for ((qid, labels) in answersByQid) {
                        putJsonObject(qid) {
                            putJsonArray("answers") { labels.forEach { add(it) } }
                        }
                    }
                }
            }
        }.toString()

    /** MCP elicitation we can't render — decline instead of hanging the turn. */
    fun encodeElicitationDecline(requestId: JsonElement): String = buildJsonObject {
        put("id", requestId)
        putJsonObject("result") {
            put("action", "decline")
            put("content", JsonNull)
        }
    }.toString()

    /** Generic refusal for server requests we don't implement
     *  (item/permissions/requestApproval, item/tool/call, attestation…) —
     *  a JSON-RPC error response; codex fails that callback and the turn
     *  continues instead of hanging forever on an unanswered request. */
    fun encodeErrorResponse(requestId: JsonElement, message: String): String = buildJsonObject {
        put("id", requestId)
        putJsonObject("error") {
            put("code", -32601)
            put("message", message)
        }
    }.toString()

    // ────────── Decoding: server → client ──────────

    sealed interface Incoming {
        /** Server-initiated request — MUST be answered (has an id). */
        data class ServerReq(val id: JsonElement, val method: String, val params: JsonObject) : Incoming
        /** Fire-and-forget notification. */
        data class Notification(val method: String, val params: JsonObject) : Incoming
        /** Response to one of OUR requests. [error] non-null on failure. */
        data class Response(val id: Long?, val result: JsonObject?, val error: JsonObject?) : Incoming
    }

    fun parseLine(line: String): Incoming? {
        val t = line.trim()
        if (!t.startsWith("{")) return null
        val obj = SilentlyTry.logged("SshAi-CodexApp", "parse rpc line") {
            json.parseToJsonElement(t).jsonObject
        } ?: return null
        val method = (obj["method"] as? kotlinx.serialization.json.JsonPrimitive)?.contentOrNull
        val id = obj["id"]
        val params = SilentlyTry.logged("SshAi-CodexApp", "rpc params obj") { obj["params"]?.jsonObject }
            ?: JsonObject(emptyMap())
        return when {
            method != null && id != null -> Incoming.ServerReq(id, method, params)
            method != null -> Incoming.Notification(method, params)
            id != null -> Incoming.Response(
                id = (id as? kotlinx.serialization.json.JsonPrimitive)?.contentOrNull?.toLongOrNull(),
                result = SilentlyTry.logged("SshAi-CodexApp", "rpc result obj") { obj["result"]?.jsonObject },
                error = SilentlyTry.logged("SshAi-CodexApp", "rpc error obj") { obj["error"]?.jsonObject },
            )
            else -> null
        }
    }

    /**
     * App approval tier → (approvalPolicy, sandbox). Now that approvals are
     * ANSWERABLE (live cards), SAFE finally gets codex's own interactive
     * default — `on-request` + `workspace-write` — instead of the read-only
     * straitjacket the non-interactive exec path needed. AUTO / YOLO keep
     * byte-identical semantics with the exec flags.
     */
    fun approvalToPolicy(mode: AgentApprovalMode): Pair<String, String> = when (mode) {
        AgentApprovalMode.SAFE -> "on-request" to "workspace-write"
        AgentApprovalMode.AUTO -> "never" to "workspace-write"
        AgentApprovalMode.YOLO -> "never" to "danger-full-access"
    }

    /**
     * `item/tool/requestUserInput` params → (question-id ordered list,
     * renderable questions). Options may be null (free-form question we
     * can't render — the caller auto-answers those with an empty pick).
     */
    fun parseUserInputQuestions(
        params: JsonObject,
    ): List<Pair<String, AgentMessage.AskUserQuestion.Question>> {
        val arr = SilentlyTry.logged("SshAi-CodexApp", "questions array") { params["questions"]?.jsonArray }
            ?: return emptyList()
        return arr.mapNotNull { q ->
            SilentlyTry.logged("SshAi-CodexApp", "question obj") {
                val o = q.jsonObject
                val qid = o.str("id") ?: return@logged null
                val options = o["options"]?.let { el ->
                    if (el is JsonNull) null
                    else el.jsonArray.mapNotNull { opt ->
                        SilentlyTry.logged("SshAi-CodexApp", "option obj") {
                            val oo = opt.jsonObject
                            AgentMessage.AskUserQuestion.Option(
                                label = oo.str("label").orEmpty(),
                                description = oo.str("description").orEmpty(),
                            )
                        }
                    }?.filter { it.label.isNotBlank() }
                }.orEmpty()
                qid to AgentMessage.AskUserQuestion.Question(
                    question = o.str("question").orEmpty(),
                    header = o.str("header").orEmpty(),
                    options = options,
                    multiSelect = false,
                )
            }
        }
    }

    internal fun JsonObject.str(key: String): String? =
        (this[key] as? kotlinx.serialization.json.JsonPrimitive)?.contentOrNull

    internal fun JsonObject.long(key: String): Long? =
        (this[key] as? kotlinx.serialization.json.JsonPrimitive)?.contentOrNull?.toLongOrNull()
}
