package ai.eight24family.conch

import ai.eight24family.conch.agent.claude.ClaudeSpec
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The "is the turn still running?" verdict — the signal behind the thinking
 * indicator and the Stop button. It had NO coverage, which is why it kept
 * regressing.
 *
 * Record layout is [ClaudeSpec.projectTurnStateRecords]'s, 9 fields:
 *   0 type · 1 isMeta · 2 hasToolResult · 3 hasToolUse · 4 outTokens
 *   5 messageId · 6 timestamp · 7 text(160) · 8 stopReason
 */
class ClaudeTurnStateTest {

    private fun rec(
        type: String,
        meta: Boolean = false,
        toolResult: Boolean = false,
        toolUse: Boolean = false,
        tokens: Long = 0,
        id: String = "",
        ts: String = "",
        text: String = "",
        stop: String = "",
    ) = listOf(type, meta.toString(), toolResult.toString(), toolUse.toString(), tokens.toString(), id, ts, text, stop)

    private fun userPrompt(text: String = "do the thing", ts: String = "2026-07-29T10:00:00.000Z") =
        rec("user", text = text, ts = ts)

    private fun endTurn(text: String = "done", tokens: Long = 120, id: String = "msg_1") =
        rec("assistant", tokens = tokens, id = id, text = text, stop = "end_turn")

    /** Exactly what Claude Code appends when a slash command runs. */
    private fun slashCommandEcho() = rec(
        "user",
        meta = true,
        text = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.",
    )

    private val fresh = 1_000L
    private val ancient = 30 * 60_000L

    // ── the reported bug ──────────────────────────────────────────────────────

    @Test
    fun `a slash command after the reply does not restart thinking`() {
        // /model opus on the fly: end_turn, then the CLI's own meta echo.
        val sig = ClaudeSpec.inferTurnState(listOf(userPrompt(), endTurn(), slashCommandEcho()), fresh)
        assertFalse("meta echo must not relight the spinner", sig.inFlight)
        assertTrue("and the stuck-turn reconcile must stay armed", sig.turnComplete)
    }

    @Test
    fun `an image-dimension carrier row does not restart thinking`() {
        val carrier = rec("user", meta = true, text = "[Image: original 1440x3120, displayed at 923x2000.]")
        val sig = ClaudeSpec.inferTurnState(listOf(userPrompt(), endTurn(), carrier), fresh)
        assertFalse(sig.inFlight)
        assertTrue(sig.turnComplete)
    }

    @Test
    fun `the working timer ignores a meta row and keeps the real prompt`() {
        val sig = ClaudeSpec.inferTurnState(
            listOf(userPrompt(ts = "2026-07-29T10:00:00.000Z"), endTurn(), slashCommandEcho()),
            fresh,
        )
        assertEquals(java.time.Instant.parse("2026-07-29T10:00:00.000Z").toEpochMilli(), sig.turnStartMs)
    }

    // ── the verdicts that must NOT change ─────────────────────────────────────

    @Test
    fun `a fresh prompt with no reply yet is working`() {
        val sig = ClaudeSpec.inferTurnState(listOf(userPrompt()), fresh)
        assertTrue(sig.inFlight)
        assertTrue("thinking, not tooling", sig.thinking)
        assertFalse(sig.turnComplete)
    }

    @Test
    fun `a tool_result with no reply yet is working`() {
        val recs = listOf(userPrompt(), rec("assistant", toolUse = true, stop = "tool_use"), rec("user", toolResult = true))
        assertTrue(ClaudeSpec.inferTurnState(recs, fresh).inFlight)
    }

    @Test
    fun `a tool_use stop_reason is working`() {
        val recs = listOf(userPrompt(), rec("assistant", toolUse = true, text = "running", stop = "tool_use"))
        assertTrue(ClaudeSpec.inferTurnState(recs, ancient).inFlight)
    }

    @Test
    fun `end_turn is done`() {
        val sig = ClaudeSpec.inferTurnState(listOf(userPrompt(), endTurn()), fresh)
        assertFalse(sig.inFlight)
        assertTrue(sig.turnComplete)
    }

    @Test
    fun `an interrupt is done - and it is not a meta row`() {
        val recs = listOf(userPrompt(), rec("user", text = "[Request interrupted by user]"))
        val sig = ClaudeSpec.inferTurnState(recs, fresh)
        assertFalse(sig.inFlight)
    }

    @Test
    fun `a long silent research turn is NOT killed`() {
        // Frozen 30 min mid-tool: real subagent work, must stay working.
        val recs = listOf(userPrompt(), rec("assistant", toolUse = true, stop = "tool_use"))
        assertTrue(ClaudeSpec.inferTurnState(recs, ancient).inFlight)
    }

    @Test
    fun `a dead turn stuck on a tool_result eventually clears`() {
        val recs = listOf(userPrompt(), rec("assistant", toolUse = true, stop = "tool_use"), rec("user", toolResult = true))
        assertTrue("still working while fresh", ClaudeSpec.inferTurnState(recs, fresh).inFlight)
        assertFalse("but not forever", ClaudeSpec.inferTurnState(recs, ancient).inFlight)
    }

    @Test
    fun `a prompt that never got an answer eventually clears`() {
        assertFalse(ClaudeSpec.inferTurnState(listOf(userPrompt()), ancient).inFlight)
    }

    @Test
    fun `tokens accumulate over the turn and reset on the next prompt`() {
        val recs = listOf(
            userPrompt(),
            rec("assistant", tokens = 40, id = "a"),
            rec("assistant", tokens = 90, id = "a"), // same message id → max, not sum
            rec("assistant", tokens = 10, id = "b", stop = "end_turn", text = "ok"),
        )
        assertEquals(100L, ClaudeSpec.inferTurnState(recs, fresh).tokens)
    }

    @Test
    fun `an empty tail says nothing`() {
        val sig = ClaudeSpec.inferTurnState(emptyList(), fresh)
        assertFalse(sig.inFlight)
        assertFalse(sig.turnComplete)
    }

    @Test
    fun `a window of only meta rows does not claim a turn is running`() {
        assertFalse(ClaudeSpec.inferTurnState(listOf(slashCommandEcho(), slashCommandEcho()), fresh).inFlight)
    }
}
