package ai.eight24family.conch

import ai.eight24family.conch.agent.AgentMessage
import ai.eight24family.conch.agent.codex.CodexAppServerEvents
import ai.eight24family.conch.agent.codex.CodexAppServerWire
import ai.eight24family.conch.data.prefs.AgentApprovalMode
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.contentOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the `codex app-server` JSON-RPC wire shapes (verified against the
 * TS bindings generated by codex-cli 0.139.0) and the v2 notification →
 * AgentMessage mapping. If codex changes the protocol, these are the
 * tests that catch it BEFORE the phone does.
 */
class CodexAppServerWireTest {

    private val json = Json { ignoreUnknownKeys = true }

    // ───────────────── encoding ─────────────────

    @Test
    fun `initialize carries clientInfo and experimentalApi`() {
        val line = CodexAppServerWire.encodeInitialize(1, "1.0.9")
        val o = json.parseToJsonElement(line).jsonObject
        assertEquals("initialize", o["method"]?.jsonPrimitive?.contentOrNull)
        assertEquals("1", o["id"]?.jsonPrimitive?.contentOrNull)
        val params = o["params"]!!.jsonObject
        assertEquals("conch", params["clientInfo"]!!.jsonObject["name"]?.jsonPrimitive?.contentOrNull)
        assertEquals("true", params["capabilities"]!!.jsonObject["experimentalApi"]?.jsonPrimitive?.contentOrNull)
        // No "jsonrpc" field — codex app-server speaks JSON-RPC lite.
        assertNull(o["jsonrpc"])
    }

    @Test
    fun `turn start carries text input with text_elements and per-turn overrides`() {
        val line = CodexAppServerWire.encodeTurnStart(
            7, "thr_1", "fix the bug", model = "gpt-5.5", effort = "xhigh",
            approval = AgentApprovalMode.SAFE, cwd = "/repo",
        )
        val o = json.parseToJsonElement(line).jsonObject
        assertEquals("turn/start", o["method"]?.jsonPrimitive?.contentOrNull)
        val p = o["params"]!!.jsonObject
        assertEquals("thr_1", p["threadId"]?.jsonPrimitive?.contentOrNull)
        assertEquals("gpt-5.5", p["model"]?.jsonPrimitive?.contentOrNull)
        assertEquals("xhigh", p["effort"]?.jsonPrimitive?.contentOrNull)
        assertEquals("/repo", p["cwd"]?.jsonPrimitive?.contentOrNull)
        assertEquals("on-request", p["approvalPolicy"]?.jsonPrimitive?.contentOrNull)
        assertTrue(line.contains("\"type\":\"text\""))
        assertTrue(line.contains("\"text\":\"fix the bug\""))
        assertTrue(line.contains("\"text_elements\":[]"))
    }

    @Test
    fun `turn start emits localImage input items for attached images`() {
        val line = CodexAppServerWire.encodeTurnStart(
            8, "thr_2", "what is this?", model = null, effort = null,
            approval = null, cwd = null,
            imagePaths = listOf("/home/user/.uploads/a.png", "/home/user/.uploads/b.jpg"),
        )
        val input = json.parseToJsonElement(line).jsonObject["params"]!!
            .jsonObject["input"]!!.jsonArray
        // text item first, then one localImage item per path (v2 UserInput shape).
        assertEquals("text", input[0].jsonObject["type"]?.jsonPrimitive?.contentOrNull)
        assertEquals("localImage", input[1].jsonObject["type"]?.jsonPrimitive?.contentOrNull)
        assertEquals("/home/user/.uploads/a.png", input[1].jsonObject["path"]?.jsonPrimitive?.contentOrNull)
        assertEquals("localImage", input[2].jsonObject["type"]?.jsonPrimitive?.contentOrNull)
        assertEquals("/home/user/.uploads/b.jpg", input[2].jsonObject["path"]?.jsonPrimitive?.contentOrNull)
    }

    @Test
    fun `turn start with no images has only the text item`() {
        val line = CodexAppServerWire.encodeTurnStart(
            9, "thr_3", "hi", model = null, effort = null, approval = null, cwd = null,
        )
        val input = json.parseToJsonElement(line).jsonObject["params"]!!
            .jsonObject["input"]!!.jsonArray
        assertEquals(1, input.size)
        assertEquals("text", input[0].jsonObject["type"]?.jsonPrimitive?.contentOrNull)
    }

    @Test
    fun `review start defaults to uncommitted changes inline`() {
        val p = json.parseToJsonElement(
            CodexAppServerWire.encodeReviewStart(11, "thr_r", baseBranch = null)
        ).jsonObject
        assertEquals("review/start", p["method"]?.jsonPrimitive?.contentOrNull)
        val params = p["params"]!!.jsonObject
        assertEquals("thr_r", params["threadId"]?.jsonPrimitive?.contentOrNull)
        assertEquals("inline", params["delivery"]?.jsonPrimitive?.contentOrNull)
        assertEquals("uncommittedChanges", params["target"]!!.jsonObject["type"]?.jsonPrimitive?.contentOrNull)
    }

    @Test
    fun `review start against a base branch carries the branch`() {
        val target = json.parseToJsonElement(
            CodexAppServerWire.encodeReviewStart(12, "thr_r", baseBranch = "main")
        ).jsonObject["params"]!!.jsonObject["target"]!!.jsonObject
        assertEquals("baseBranch", target["type"]?.jsonPrimitive?.contentOrNull)
        assertEquals("main", target["branch"]?.jsonPrimitive?.contentOrNull)
    }

    @Test
    fun `approval mode mapping`() {
        assertEquals("on-request" to "workspace-write", CodexAppServerWire.approvalToPolicy(AgentApprovalMode.SAFE))
        assertEquals("never" to "workspace-write", CodexAppServerWire.approvalToPolicy(AgentApprovalMode.AUTO))
        assertEquals("never" to "danger-full-access", CodexAppServerWire.approvalToPolicy(AgentApprovalMode.YOLO))
    }

    @Test
    fun `approval decision echoes the server request id verbatim`() {
        // Server request ids can be numbers OR strings (RequestId = string|number).
        val numReq = CodexAppServerWire.parseLine(
            """{"method":"item/commandExecution/requestApproval","id":42,"params":{"threadId":"t","turnId":"u","itemId":"i","startedAtMs":1,"command":"rm -rf /tmp/x"}}"""
        ) as CodexAppServerWire.Incoming.ServerReq
        val resp = CodexAppServerWire.encodeApprovalDecision(numReq.id, "accept")
        val o = json.parseToJsonElement(resp).jsonObject
        assertEquals("42", o["id"]?.jsonPrimitive?.contentOrNull)
        assertEquals("accept", o["result"]!!.jsonObject["decision"]?.jsonPrimitive?.contentOrNull)
    }

    @Test
    fun `user input answers map question ids to answer arrays`() {
        val req = CodexAppServerWire.parseLine(
            """{"method":"item/tool/requestUserInput","id":"req-9","params":{"threadId":"t","turnId":"u","itemId":"i","questions":[]}}"""
        ) as CodexAppServerWire.Incoming.ServerReq
        val resp = CodexAppServerWire.encodeUserInputAnswers(
            req.id, linkedMapOf("q1" to listOf("Option A"), "q2" to emptyList()),
        )
        val o = json.parseToJsonElement(resp).jsonObject
        assertEquals("req-9", o["id"]?.jsonPrimitive?.contentOrNull)
        val answers = o["result"]!!.jsonObject["answers"]!!.jsonObject
        assertTrue(answers["q1"].toString().contains("Option A"))
        assertTrue(answers["q2"].toString().contains("\"answers\":[]"))
    }

    // ───────────────── decoding / routing ─────────────────

    @Test
    fun `routing distinguishes requests notifications and responses`() {
        assertTrue(
            CodexAppServerWire.parseLine("""{"method":"item/fileChange/requestApproval","id":1,"params":{}}""")
                is CodexAppServerWire.Incoming.ServerReq
        )
        assertTrue(
            CodexAppServerWire.parseLine("""{"method":"turn/completed","params":{"threadId":"t","turn":{"id":"u"}}}""")
                is CodexAppServerWire.Incoming.Notification
        )
        val resp = CodexAppServerWire.parseLine("""{"id":5,"result":{"thread":{"id":"thr_x"}}}""")
            as CodexAppServerWire.Incoming.Response
        assertEquals(5L, resp.id)
        assertNull(resp.error)
        val err = CodexAppServerWire.parseLine("""{"id":6,"error":{"code":-32600,"message":"bad"}}""")
            as CodexAppServerWire.Incoming.Response
        assertEquals(6L, err.id)
        assertTrue(err.error != null)
        assertNull(CodexAppServerWire.parseLine("not json"))
    }

    @Test
    fun `requestUserInput questions parse into card shape`() {
        val params = json.parseToJsonElement(
            """{"threadId":"t","turnId":"u","itemId":"i","questions":[
               {"id":"q1","header":"Approach","question":"Which approach?","isOther":false,"isSecret":false,
                "options":[{"label":"Fast","description":"quick hack"},{"label":"Right","description":"proper fix"}]},
               {"id":"q2","header":"Name","question":"Type a name","isOther":true,"isSecret":false,"options":null}
            ]}"""
        ).jsonObject
        val parsed = CodexAppServerWire.parseUserInputQuestions(params)
        assertEquals(2, parsed.size)
        assertEquals("q1", parsed[0].first)
        val q1 = parsed[0].second
        assertEquals("Which approach?", q1.question)
        assertEquals("Approach", q1.header)
        assertEquals(2, q1.options.size)
        assertEquals("Fast", q1.options[0].label)
        assertEquals("proper fix", q1.options[1].description)
        assertFalse(q1.multiSelect)
        // Free-form question (no options) parses but is not renderable.
        assertTrue(parsed[1].second.options.isEmpty())
    }

    // ───────────────── item mapping ─────────────────

    private fun item(s: String) = json.parseToJsonElement(s).jsonObject

    @Test
    fun `agentMessage item completes into AssistantText with turn-scoped id`() {
        val out = CodexAppServerEvents.mapItem(
            item("""{"type":"agentMessage","id":"item_3","text":"done!"}"""),
            started = false, turnId = "turn_9",
        )
        assertEquals(1, out.size)
        val a = out.first() as AgentMessage.AssistantText
        assertEquals("codexapp_turn_9_item_3", a.id)
        assertEquals("done!", a.text)
        // started carries no text yet → nothing.
        assertTrue(CodexAppServerEvents.mapItem(item("""{"type":"agentMessage","id":"item_3"}"""), true, "turn_9").isEmpty())
    }

    @Test
    fun `commandExecution maps exec note then ToolResult with error flag`() {
        val started = CodexAppServerEvents.mapItem(
            item("""{"type":"commandExecution","id":"item_1","command":"ls -la","status":"inProgress"}"""),
            started = true, turnId = "turn_1",
        )
        assertTrue((started.first() as AgentMessage.EventNote).label.contains("exec · ls -la"))
        val done = CodexAppServerEvents.mapItem(
            item("""{"type":"commandExecution","id":"item_1","command":"ls -la","status":"failed","aggregatedOutput":"boom","exitCode":1}"""),
            started = false, turnId = "turn_1",
        )
        val tr = done.first() as AgentMessage.ToolResult
        assertEquals("codexapp_turn_1_item_1", tr.toolUseId)
        assertTrue(tr.output.contains("$ ls -la"))
        assertTrue(tr.output.contains("boom"))
        assertTrue(tr.isError)
    }

    @Test
    fun `contextCompaction item drives the live compacting row`() {
        val started = CodexAppServerEvents.mapItem(
            item("""{"type":"contextCompaction","id":"item_5"}"""), started = true, turnId = "turn_2",
        ).first() as AgentMessage.System
        assertEquals("compacting", started.subtype)
        val done = CodexAppServerEvents.mapItem(
            item("""{"type":"contextCompaction","id":"item_5"}"""), started = false, turnId = "turn_2",
        ).first() as AgentMessage.System
        assertEquals("compact_done", done.subtype)
        // SAME id → the animated row morphs in place into the divider.
        assertEquals(started.id, done.id)
    }

    @Test
    fun `fileChange item upserts a patch note in place`() {
        val started = CodexAppServerEvents.mapItem(
            item("""{"type":"fileChange","id":"item_7","status":"inProgress","changes":[{"path":"src/A.kt","kind":{"type":"update"},"diff":""}]}"""),
            started = true, turnId = "turn_3",
        ).first() as AgentMessage.EventNote
        assertTrue(started.label.contains("patching · A.kt"))
        val done = CodexAppServerEvents.mapItem(
            item("""{"type":"fileChange","id":"item_7","status":"completed","changes":[{"path":"src/A.kt","kind":{"type":"update"},"diff":""}]}"""),
            started = false, turnId = "turn_3",
        ).first() as AgentMessage.EventNote
        assertTrue(done.label.contains("patched · A.kt"))
        assertEquals(started.id, done.id)
    }

    @Test
    fun `unknown item type surfaces generically`() {
        val out = CodexAppServerEvents.mapItem(
            item("""{"type":"imageGeneration","id":"item_8","status":"completed","result":"img"}"""),
            started = false, turnId = "turn_4",
        )
        assertEquals(1, out.size)
        assertTrue((out.first() as AgentMessage.EventNote).label.contains("imageGeneration · completed")
            || (out.first() as AgentMessage.EventNote).label.contains("imageGeneration"))
    }

    @Test
    fun `plan update renders live progress with steps in detail`() {
        val params = json.parseToJsonElement(
            """{"threadId":"t","turnId":"turn_5","explanation":null,"plan":[
                {"step":"read code","status":"completed"},
                {"step":"fix bug","status":"inProgress"},
                {"step":"run tests","status":"pending"}]}"""
        ).jsonObject
        val n = CodexAppServerEvents.mapPlanUpdate(params, "turn_5").first() as AgentMessage.EventNote
        assertTrue(n.label.contains("plan · 1/3"))
        assertTrue(n.detail!!.contains("✓ read code"))
        assertTrue(n.detail!!.contains("▸ fix bug"))
        assertEquals("codexapp-plan-turn_5", n.id)
    }

    @Test
    fun `retriable error is a WARN note terminal error is an Error`() {
        val retry = CodexAppServerEvents.mapError(
            json.parseToJsonElement("""{"error":{"message":"rate limited"},"willRetry":true,"threadId":"t","turnId":"u"}""").jsonObject
        ).first()
        assertTrue(retry is AgentMessage.EventNote && retry.tone == AgentMessage.EventNote.Tone.WARN)
        val fatal = CodexAppServerEvents.mapError(
            json.parseToJsonElement("""{"error":{"message":"boom"},"willRetry":false,"threadId":"t","turnId":"u"}""").jsonObject
        ).first()
        assertTrue(fatal is AgentMessage.Error)
        assertEquals("boom", (fatal as AgentMessage.Error).text)
    }
}
